spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transaction-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #listener:
     # ack-mode: MANUAL
      #properties:
       # spring:
        #  json:
         #   trusted:
          #    packages: com.digital.backend.events
           # value:
            #  default:
             #   type: com.digital.backend.events.TransactionEvent
        #spring.json.trusted.packages: "*"
        #spring.json.value.default.type: com.digital.backend.events.TransactionEvent
