package com.db.payment.integration;

import com.db.payment.entity.PaymentEntity;
import com.db.payment.repository.PaymentRepository;
import com.digital.backend.model.enums.PaymentOperation;
import com.digital.backend.model.enums.PaymentStatus;
import com.digital.backend.model.enums.PaymentType;
import com.digital.backend.model.paymentservice.AccountInfo;
import com.digital.backend.model.paymentservice.Payment;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Integration tests for the payment creation flow:
 * REST controller -> PaymentService -> PaymentRepository (H2) -> PaymentEventPublisher (mocked Kafka).
 */
@Transactional
class PaymentIntegrationTest extends BaseIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private PaymentRepository paymentRepository;

    @Test
    void createPayment_happyPath_persistsRecordAndPublishesKafkaEvent() throws Exception {
        String fromAccountNumber = "1234567890";

        AccountInfo accountInfo = AccountInfo.builder()
                .fromAccountNumber(fromAccountNumber)
                .fromIFSCCode("SBIN0001234")
                .build();

        Payment payment = Payment.builder()
                .paymentAccountInfo(accountInfo)
                .amount(1500.00)
                .paymentType(PaymentType.CREDIT)
                .paymentOperation(PaymentOperation.NEFT)
                .build();

        mockMvc.perform(post("/api/v1/payment/{fromAccountNumber}", fromAccountNumber)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(payment)))
                .andExpect(status().isOk());

        // ---- Verify persistence: this only passes if Flyway actually created the
        //      "payment" table/schema against H2 and JPA could write to it. ----
        List<PaymentEntity> savedPayments = paymentRepository.findAll();
        assertEquals(1, savedPayments.size(), "Exactly one payment record should have been saved");

        PaymentEntity savedEntity = savedPayments.get(0);
        assertEquals(fromAccountNumber, savedEntity.getFromAccountNumber());
        assertEquals("SBIN0001234", savedEntity.getFromIFSCCode());
        assertEquals(1500.00, savedEntity.getAmount());
        assertEquals(PaymentType.CREDIT, savedEntity.getPaymentType());
        assertEquals(PaymentOperation.NEFT, savedEntity.getPaymentOperation());
        assertEquals(PaymentStatus.INITIATED, savedEntity.getPaymentStatus());
        assertNotNull(savedEntity.getPaymentId(), "paymentId should be generated by @PrePersist");

        // ---- Verify the Kafka publish via the mocked KafkaTemplate ----
        ArgumentCaptor<String> topicCaptor = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> keyCaptor = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<Object> payloadCaptor = ArgumentCaptor.forClass(Object.class);

        verify(kafkaTemplate, times(1))
                .send(topicCaptor.capture(), keyCaptor.capture(), payloadCaptor.capture());

        assertEquals("payment-request-event", topicCaptor.getValue());
        assertEquals(savedEntity.getPaymentId(), keyCaptor.getValue());

        String publishedJson = (String) payloadCaptor.getValue();
        assertTrue(publishedJson.contains(fromAccountNumber),
                "Published event payload should contain the from-account number");
        assertTrue(publishedJson.contains(savedEntity.getPaymentId()),
                "Published event payload should contain the generated paymentId");
    }

    @Test
    void createPayment_missingFromAccountDetails_returnsBadRequestAndSkipsDownstreamWork() throws Exception {
        // No paymentAccountInfo at all -> fails the controller-level pre-check
        // in PaymentControllerImpl before the service/repository/Kafka are ever touched.
        Payment invalidPayment = Payment.builder()
                .amount(500.00)
                .paymentType(PaymentType.DEBIT)
                .paymentOperation(PaymentOperation.IMPS)
                .build();

        mockMvc.perform(post("/api/v1/payment/{fromAccountNumber}", "9999999999")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidPayment)))
                .andExpect(status().isBadRequest());

        assertEquals(0, paymentRepository.count(), "No payment should be persisted for an invalid request");
        verifyNoInteractions(kafkaTemplate);
    }
}