package com.db.transaction.integration;

import com.db.transaction.entity.TransactionEntity;
import com.db.transaction.repository.TransactionRepository;
import com.db.transaction.scheduler.TransactionScheduler;
import com.digital.backend.model.TransactionInput;
import com.digital.backend.model.enums.TransactionStatus;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

class TransactionIntegrationTest extends BaseIntegrationTest {

    private static final String KAFKA_TOPIC = "transaction-events";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TransactionRepository transactionRepository;

    @Autowired
    private TransactionScheduler transactionScheduler;

    // Instantiated directly rather than @Autowired: no ObjectMapper bean is
    // exposed in this context, and the test only needs it to serialize request
    // bodies for MockMvc, so the app's configured instance isn't required.
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void cleanUp() {
        transactionRepository.deleteAll();
    }

    /**
     * Happy path:
     * 1. POST a deposit through MockMvc.
     * 2. Confirm via TransactionRepository that the row was persisted with status
     *    OPENED — this also proves the JPA schema (generated by Hibernate for this
     *    test profile, since Flyway's Postgres-only DDL isn't H2-compatible; see
     *    application-test.yml) matches the entity mapping, since the save/find
     *    would blow up otherwise.
     * 3. Deposits don't push a Kafka event by themselves in this codebase — that
     *    happens when TransactionScheduler.processTransaction() picks up OPENED
     *    rows. So we invoke that method directly (rather than waiting on the cron
     *    trigger) and verify the mocked KafkaTemplate was called with the right
     *    topic and a non-null JSON payload.
     */
    @Test
    void depositMoney_happyPath_persistsRowAndPublishesKafkaEventViaScheduler() throws Exception {
        TransactionInput deposit = TransactionInput.builder()
                .toAccountNumber(1001L)
                .toIFSCCode("HDFC0001234")
                .amount(5000.00)
                .build();

        mockMvc.perform(post("/api/v1/transaction/deposit/{toAccountNumber}", 1001L)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(deposit)))
                .andExpect(status().isOk());

        List<TransactionEntity> saved = transactionRepository.findAll();
        assertEquals(1, saved.size());

        TransactionEntity persisted = saved.get(0);
        assertNotNull(persisted.getTransactionNumber());
        assertEquals(1001L, persisted.getToAccountNumber());
        assertEquals(5000.00, persisted.getAmount());
        assertEquals(TransactionStatus.OPENED, persisted.getStatus());

        // Trigger the batch job that turns OPENED rows into Kafka events.
        transactionScheduler.processTransaction();

        verify(kafkaTemplate).send(eq(KAFKA_TOPIC), anyString(), anyString());

        Optional<TransactionEntity> afterSchedule =
                transactionRepository.findTransactionByTransactionNumber(persisted.getTransactionNumber());
        assertTrue(afterSchedule.isPresent());
        assertEquals(TransactionStatus.INPROGRESS, afterSchedule.get().getStatus());
    }

    /**
     * TransactionControllerImpl.depositMoney() manually rejects a missing
     * toAccountNumber with a 400 before the service layer is ever invoked.
     * No row should be persisted as a result.
     */
    @Test
    void depositMoney_missingToAccountNumber_returnsBadRequestAndPersistsNothing() throws Exception {
        TransactionInput invalidDeposit = TransactionInput.builder()
                .toIFSCCode("HDFC0001234")
                .amount(5000.00)
                .build();

        mockMvc.perform(post("/api/v1/transaction/deposit/{toAccountNumber}", 1001L)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidDeposit)))
                .andExpect(status().isBadRequest());

        assertEquals(0, transactionRepository.count());
    }
}