server:
  port: 8083

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.digitalbanking.*"

# Kafka Topics
kafka:
  topics:
    payment-initiated: payment.initiated
    payment-completed: payment.completed
    payment-failed: payment.failed
    account-debit-request: account.debit.request
    account-debit-response: account.debit.response
    transaction-record-request: transaction.record.request


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    doc-expansion: none
    model-and-view-allowed: true