spring:
  application:
    name: account-service

  flyway:
    enabled: true
    check-location: true
    schemas: account
    locations: classpath:db/migrations

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schemas=account?serverTimezone=Asia/Calcutta
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: account

  logging:
    level:
      org:
        flywaydb: DEBUG