spring:
  application:
    name: account-service

  flyway:
    enabled: true
    check-location: true
    schemas: account
    locations: classpath:db/migrations

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schemas=account?serverTimezone=Asia/Calcutta
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: account

  logging:
    config: classpath:logback-spring.xml
    level:
      org:
        flywaydb: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    doc-expansion: none
    model-and-view-allowed: true