ALTER TABLE account
ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE branch
ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE customer
ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;

